version: '3.6'

services:
  zookeeperservice:
    image: bitnami/zookeeper:latest
    hostname: 10.4.1.29
    container_name: zookeeper
    networks:
      - fitkartnetwork
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafkaservice:
    image: bitnami/kafka:latest
    hostname: 10.4.1.30
    container_name: fitkart_kafka
    networks:
      - fitkartnetwork
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeperservice:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.4.1.30:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS="emailservice:1:1:compact"
      - AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeperservice
networks:
  fitkartnetwork:
